import sizes from './sizes';
import overlay from './overlay.svg';

export default {
  content: {
    width: '20%',
    height: '40%',
    margin: '0 auto',
    display: 'inline-block',
    position: 'relative',
    cursor: 'pointer',
    marginBottom: '-3.5px',

    '&:hover button': {
      opacity: '1',
      transition: '0.5s',
    },
    [sizes.down('lg')]: {
      width: '25%',
      height: '50%',
    },
    [sizes.down('md')]: {
      width: '25%',
      height: '20%',
    },
    [sizes.down('xs')]: {
      width: '100%',
      height: '10%',
    },
  },
  seeMore: {
    background: 'rgba(255, 255, 255, 0.5)',
    position: 'absolute',
    border: 'none',
    right: '0',
    bottom: '0',
    color: 'white',
    width: '60px',
    height: '30px',
    textAlign: 'center',
    lineHeight: '30px',
    textTransform: 'uppercase',
  },
  showButton: {
    width: '100%',
    height: '30px',
    position: 'absolute',
    display: 'inline-block',
    top: '50%',
    left: '50%',
    marginLeft: '-50%',
    marginTop: '-15px',
    textAlign: 'center',
    outline: 'none',
    background: 'rgba(255, 255, 255, 0.5)',
    fontSize: '1rem',
    lineHeight: '30px',
    color: 'white',
    textTransform: 'uppercase',
    border: 'none',
    opacity: '0',
  },
  overlay: {
    opacity: '0',
    zIndex: '0',
    width: '100%',
    height: '100%',
    transition: 'transform 0.6s ease-in-out',
    transform: 'scale(0.1)',
    backgroundColor: '#000000',
    //background by svgbackgrounds.com
    backgroundImage: `url(${overlay})`,
  },
  showOverlay: {
    opacity: '1',
    transform: 'scale(50)',
    zIndex: '25',
    position: 'absolute',
  },
  overlayMessage: {
    position: 'fixed',
    left: '0',
    right: '0',
    top: '0',
    bottom: '0',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '4rem',
    transform: 'scale(0.1)',
    opacity: '0',
    color: 'white',
    '& h1': {
      fontWeight: '400',
      textShadow: '1px 2px white',
      background: 'rgba(255, 255, 255, 0.2)',
      width: '100%',
      textAlign: 'center',
      marginBottom: '0',
      padding: '1rem',
      textTransform: 'uppercase',
    },
    '& p': {
      fontSize: '2rem',
      fontWeight: '100',
      textAlign: 'center',
    },
  },

  showMessage: {
    opacity: '1',
    transform: 'scale(0.5)',
    zIndex: '35',
    transition: 'all 0.4s ease-in-out',
    transitionDelay: '0.3s',
  },
};
